server:
  port: 9001

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_account
    username: postgres
    password: kysz
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  security:
    oauth2:
      client:
        registration:
          transaction-client:
            client-id: transaction-service
            client-secret: txn-secret
            authorization-grant-type: client_credentials
            scope: transaction.write
        provider:
          transaction-provider:
            token-uri: http://localhost:9001/oauth2/token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

