server:
  port: 9001

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_account
    username: postgres
    password: kysz
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      # =========================
      # OAUTH2 CLIENT (Transaction Service Registration)
      # =========================
      client:
        registration:
          transaction-service:
            provider: keycloak
            client-id: account-service
            client-secret: ${ACCOUNT_SERVICE_CLIENT_SECRET:your_client_secret_here}
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/bank-realm

      # =========================
      # RESOURCE SERVER (Validate Incoming Tokens)
      # =========================
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bank-realm

# =========================
# EUREKA CONFIG
# =========================
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# =========================
# ACTUATOR
# =========================
management:
  endpoints:
    web:
      exposure:
        include: health,info
