server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: api-gateway

  # Keycloak Resource Server Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bank-realm

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        # =====================
        # AUTH SERVICE (PUBLIC)
        # =====================
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # ==========================
        # ACCOUNT SERVICE (USER JWT)
        # ==========================
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**

        # ==================================================
        # TRANSACTION SERVICE (BLOCK FRONTEND COMPLETELY)
        # ==================================================
        # ❌ NO ROUTE EXPOSED FOR /transactions/**
        # Only Account Service can call Transaction Service
        # directly via service discovery (lb://transaction-service)

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
