server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bank-realm

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # =====================
        # AUTH SERVICE (PUBLIC)
        # =====================
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # ==========================
        # ACCOUNT SERVICE (JWT)
        # ==========================
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"

        # 🚫 TRANSACTION SERVICE
        # Not exposed via gateway
