server:
  port: 9000

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_auth

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
