server:
  port: 9000

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/bank_auth
    username: postgres
    password: kysz
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
