server:
  port: 9002

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_transaction

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bank-realm
